version: "3.9"
services:
  web:
    build: ./backend
    volumes:
      - ./backend:/app/
  
nginx:
    build: ./nginx
    volumes: 
      - ./nginx/nginxdata:/var/log/nginx
    container_name: webserver
    ports:
        - 8001:8001
    restart: on-failure